### ISSUE TITLE
`estimateTransactionGasLimit` hides errors from the caller

### ISSUE THREAD

**Issue by shioju** [TrueFiEng/useDApp#1080]
**Describe the bug**
`estimateTransactionGasLimit` hides errors from the caller

**To Reproduce**
We're using `useContractFunction` to call a smart contract function. In this instance, we're expecting the function to revert with a custom error, and want to catch it and display an appropriate error message to the user.

However, we only see the `cannot estimate gas` error in the browser console, but unable to catch the error where we're calling `send`.
![screenshot-20230208-12:34:23](https://user-images.githubusercontent.com/4652591/217434615-adda0dc9-3f7a-494d-a1ce-2979dd89dc92.png)

Relevant part of `useContractFunction`'s `send` which checks gas estimate:
![screenshot-20230208-12:26:02](https://user-images.githubusercontent.com/4652591/217434803-5385d1ca-50bd-4626-9f80-d1e093874f94.png)

Relevant part of `estimateTransactionGasLimit` which catches the error but does not throw it to the caller:
![screenshot-20230208-12:39:34](https://user-images.githubusercontent.com/4652591/217435133-1883cbe6-f538-4205-8ad0-17c2b32ff1b6.png)

**Comment by shioju** [comment]
We realized that the useContractFunction `state` has an `errorHash` which can be mapped back to the custom error defined in the smart contract (e.g. using [ethers getError function](https://docs.ethers.org/v5/api/utils/abi/interface/#Interface--fragments))

**Comment by Craigson** [comment]
@shioju , I'm experiencing a similar issue - however the `state` only provides `status: "PendingSignature"` as the user has not yet interacted with their wallet.

They cannot confirm the TX as the gas estimate is `0`, and clicking reject does not return an error hash:

See the error below:

```
inpage.js:1 MetaMask - RPC Error: Internal JSON-RPC error. {code: -32603, message: 'Internal JSON-RPC error.', data: {…}}
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:17
_runReturnHandlers @ inpage.js:17
_processRequest @ inpage.js:17
await in _processRequest (async)
_handle @ inpage.js:17
handle @ inpage.js:17
_rpcRequest @ inpage.js:1
(anonymous) @ inpage.js:1
request @ inpage.js:1
(anonymous) @ web3-provider.ts:96
send @ web3-provider.ts:167
(anonymous) @ json-rpc-provider.ts:640
(anonymous) @ json-rpc-provider.ts:1
__awaiter @ json-rpc-provider.ts:1
perform @ json-rpc-provider.ts:615
(anonymous) @ base-provider.ts:1738
fulfilled @ base-provider.ts:1
Promise.then (async)
step @ base-provider.ts:1
fulfilled @ base-provider.ts:1
Promise.then (async)
step @ base-provider.ts:1
(anonymous) @ base-provider.ts:1
__awaiter @ base-provider.ts:1
estimateGas @ base-provider.ts:1732
(anonymous) @ index.ts:111
fulfilled @ index.ts:1
Promise.then (async)
step @ index.ts:1
(anonymous) @ index.ts:1
__awaiter @ index.ts:1
estimateGas @ index.ts:108
(anonymous) @ index.ts:330
fulfilled @ index.ts:1
Promise.then (async)
step @ index.ts:1
(anonymous) @ index.ts:1
__awaiter @ index.ts:1
(anonymous) @ index.ts:322
estimateContractFunctionGasLimit @ usePromiseTransaction.ts:47
(anonymous) @ useContractFunction.ts:98
handleRent @ RentalMarketplace.tsx:129
apply @ _apply.js:15
baseInvoke @ _baseInvoke.js:21
apply @ _apply.js:16
(anonymous) @ _overRest.js:32
Button._this.handleClick @ Button.js:63
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
(anonymous) @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
dispatchDiscreteEvent @ react-dom.development.js:6430
usePromiseTransaction.ts:51 Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266","to":"0x0C8E79F3534B00D9a3D4a856B665Bf4eBC22f2ba","value":{"type":"BigNumber","hex":"0x0de0b6b3a763e700"},"data":"0x7223a3c30000000000000000000000000000000000000000000000000de0b6b3a763e700000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000151800000000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":3,"message":"execution reverted","data":"0x7baa7dfa"},"stack":"{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"data\": {\n    \"code\": 3,\n    \"message\": \"execution reverted\",\n    \"data\": \"0x7baa7dfa\"\n  },\n  \"stack\": \"Error: Internal JSON-RPC error.\\n    at new n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:12:23059)\\n    at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:12:25815)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:12:26425)\\n    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:29:42701)\\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:29:43730\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:10:47625\"\n}\n  at new n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:12:23059)\n  at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:12:25815)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:12:26425)\n  at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:29:42701)\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:29:43730\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:10:47625"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at Logger.makeError (index.ts:269:1)
    at Logger.throwError (index.ts:281:1)
    at checkError (json-rpc-provider.ts:78:1)
    at Web3Provider.<anonymous> (json-rpc-provider.ts:642:1)
    at Generator.throw (<anonymous>)
    at rejected (json-rpc-provider.ts:1:1)
    ```
    
I need some way to access the error so that I can parse it using the interface, but it never reaches the dapp state.
