### ISSUE TITLE
core.constants.chainId: add Avalanche Testnet (fuji) network to list of supported networks

### ISSUE THREAD

**Issue by kamescg** [TrueFiEng/useDApp#421]
Since Avalanche has been added as a constant in the chainId file, it would be nice to also have the Avalanche Testnet (Fuji) included in available networks.

**Comment by kamescg** [comment]
Also, it would nice to add a verified multicall contract on Fuji, so it doesn't have to manually added in the configuration.

**Comment by gurunbox-contracts** [comment]
Yes, I also want to use Avalanche testnet. It is great to add Avalanche testnet to default chains. And sorry to bother you, please tell me the way to add Avalanche testnet to my project..!

**Comment by maggot0420** [comment]
@kamescg do you have any example to add Avalanche fuji multicall?

**Comment by damianlluch** [comment]
Hi, I have the same issue.

```
index.js:1 Missing multicall address for chain id 43113 
    at ChainStateProvider (http://localhost:3000/static/js/vendors~main.chunk.js:50332:5)
    at LocalMulticallProvider (http://localhost:3000/static/js/vendors~main.chunk.js:49824:5)
    at BlockNumberProvider (http://localhost:3000/static/js/vendors~main.chunk.js:50028:5)
    at Web3ReactProvider (http://localhost:3000/static/js/vendors~main.chunk.js:51790:27)
    at EthersProvider (http://localhost:3000/static/js/vendors~main.chunk.js:49764:5)
    at DAppProviderWithConfig (http://localhost:3000/static/js/vendors~main.chunk.js:49717:5)
    at ConfigProvider (http://localhost:3000/static/js/vendors~main.chunk.js:50588:5)
    at DAppProvider (http://localhost:3000/static/js/vendors~main.chunk.js:49697:5)
    at r (http://localhost:3000/static/js/vendors~main.chunk.js:102624:19)
    at Providers (http://localhost:3000/main.1247991f5f46f42d665d.hot-update.js:41:5)
    at App
    ```
    
    
any solution?

thanks

**Comment by mj426382** [comment]
We added avalanche and testnet to known chains.
