### ISSUE TITLE
Error when connected to Mumbai with Metamask wallet

### ISSUE THREAD

**Issue by burakkaraceylan** [TrueFiEng/useDApp#535]
When I connect to mumbai network with Metamask wallet I repeatedly receive the error below. it does not happen with the main Polygon network or Ethereum networks.

```
Failed to check transaction hash: undefined Error: invalid hash (argument="value", value=undefined, code=INVALID_ARGUMENT, version=providers/5.5.0)
    at Logger.makeError (index.ts:225:1)
    at Logger.throwError (index.ts:237:1)
    at Logger.throwArgumentError (index.ts:241:1)
    at Formatter.hex (formatter.ts:221:1)
    at Formatter.hash (formatter.ts:267:1)
    at Web3Provider.<anonymous> (base-provider.ts:1570:1)
    at Generator.next (<anonymous>)
    at fulfilled (base-provider.ts:1:1)
```

**Comment by mr13tech** [comment]
try to change your RPC provider. We use `useDapp` and mumbai with alchemy rpc - works as charm.

**Comment by mj426382** [comment]
As for now Mumbai network is supported :)

**Comment by bemnet16** [comment]
When I connect to mumbai network with Metamask wallet
Could not fetch chain ID. Is your RPC URL correct?
